package com.example.cheapac.presentation.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFBC140F)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDAD5)
val light_onPrimaryContainer = Color(0xFF410000)
val light_secondary = Color(0xFF414CD8)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE0E0FF)
val light_onSecondaryContainer = Color(0xFF00046A)
val light_tertiary = Color(0xFF00658D)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFC6E7FF)
val light_onTertiaryContainer = Color(0xFF001E2E)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFF8FDFF)
val light_onBackground = Color(0xFF001F25)
val light_surface = Color(0xFFF8FDFF)
val light_onSurface = Color(0xFF001F25)
val light_surfaceVariant = Color(0xFFF5DDDA)
val light_onSurfaceVariant = Color(0xFF534341)
val light_outline = Color(0xFF857370)
val light_inverseOnSurface = Color(0xFFD6F6FF)
val light_inverseSurface = Color(0xFF00363F)
val light_inversePrimary = Color(0xFFFFB4A9)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFBC140F)
val light_outlineVariant = Color(0xFFD8C2BE)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB4A9)
val dark_onPrimary = Color(0xFF690001)
val dark_primaryContainer = Color(0xFF930002)
val dark_onPrimaryContainer = Color(0xFFFFDAD5)
val dark_secondary = Color(0xFFBEC2FF)
val dark_onSecondary = Color(0xFF000AA7)
val dark_secondaryContainer = Color(0xFF252FC0)
val dark_onSecondaryContainer = Color(0xFFE0E0FF)
val dark_tertiary = Color(0xFF83CFFF)
val dark_onTertiary = Color(0xFF00344B)
val dark_tertiaryContainer = Color(0xFF004C6C)
val dark_onTertiaryContainer = Color(0xFFC6E7FF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF001F25)
val dark_onBackground = Color(0xFFA6EEFF)
val dark_surface = Color(0xFF001F25)
val dark_onSurface = Color(0xFFA6EEFF)
val dark_surfaceVariant = Color(0xFF534341)
val dark_onSurfaceVariant = Color(0xFFD8C2BE)
val dark_outline = Color(0xFFA08C89)
val dark_inverseOnSurface = Color(0xFF001F25)
val dark_inverseSurface = Color(0xFFA6EEFF)
val dark_inversePrimary = Color(0xFFBC140F)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB4A9)
val dark_outlineVariant = Color(0xFF534341)
val dark_scrim = Color(0xFF000000)

val seed = Color(0xFFD92D21)